- frontend/src/components/PaymentSelection.svelte
becaues values were accessed before they were ready it caused errors and the page to break.
Added additional checks to prevent this
> fix direct url access / hard reload causing errors

- frontend/src/app.css
- frontend/src/components/DAO/DiscussionListItem.svelte
- frontend/src/components/DAO/discussions/CommentThreadItem.svelte
- frontend/src/components/DAO/discussions/DiscussionThreadItem.svelte
- frontend/src/components/DAO/discussions/PostThreadItem.svelte
- frontend/src/components/DAO/discussions/StatusSpan.svelte
- frontend/src/routes/DAO/ShowDiscussion.svelte
- frontend/src/ts/api.ts
Further extends the capabilities of the forums:
* Lock a post.
* Delete comment and post
> Close posts / delete comments and posts for admins

- backend/main.go
- frontend/src/ts/api.ts
plus change post requests to get req
Closes https://github.com/flatfeestack/flatfeestack/issues/179
> Allow public badge to be viewed without login

- .github/workflows/deploy-monitoring.yaml
- analyzer/main.go
- fastauth/main.go
- monitoring/ansible-grafana.yaml
- monitoring/prometheus/prometheus.yml
- payout/main.go
- forgot to add the prometheus middleware 
- added the config for monitoring env
> Monitoring

- frontend/src/routes/Search.svelte
* Document that you can sponsor projects from somewhere else.
* Document that you need to have funding so your repositories actually receive contributions.
> Improve text on search page

- frontend/src/ts/api.ts
with the changed error handling, it checks each
request, and no response body (good req) caused
an error to be displayed
> fix error being displayed on response

- frontend/src/routes/Search.svelte
- frontend/src/routes/Signup.svelte
> Frontend fixes

- analyzer/Dockerfile
This should fix the build on M1 / ARM64 in general.
> Install libgit2 to an architecture-independent place

- backend/api/users.go
- backend/backend.yaml
- backend/db/users.go
- backend/main.go
- frontend/src/routes/Settings.svelte
- frontend/src/ts/api.ts
- frontend/src/types/generated-backend-types.ts
> enable user to delete the profile picture

- frontend/src/app.css
- frontend/src/components/DAO/Call.svelte
- frontend/src/routes/DAO/ShowProposal.svelte
- frontend/src/ts/daoStore.ts
With this PR, the `ShowProposal` component can decode the calls for known contracts (DAO, Membership, Wallet).
> Decode calldata for known contracts

- backend/calc.go
- backend/calc_test.go
We're seeing this issue on test, where negative contributions are saved in the database.
The main issue is that funds, that cannot be distributed today, are saved up for tomorrow, using the `future_contribution` table. The next day, if more than one person was registered for one repositories, the saved up funds from yesterday were deducted twice, as the respective code was inside a loop instead of outside.
Another issue was that `distributeFutureAdd` was not properly divided by the amount of repositories. This further contributed to the problem. If two repositories were sponsored, they both deducted the full amount of `future_contribution` from yesterday, instead of just their share.
> Fix negative contributions

- backend/api/invite.go
- frontend/src/routes/Invitations.svelte
block it in frontend and backend (direct request). user should not be allowed to invite themselves, would cause various problems
> fix user being able to invite themselves

- frontend/src/components/Header.svelte
> disable dao on production

- .github/workflows/cleanRegistry.yaml
- cleanupRegistry.sh
the script does the following:
find tags and remove them if they are older than 10 days
find manifests and delete manifests with no tags
> cleanup digitalocean registry

- backend/api/repo.go
- backend/db/analysis.go
- frontend/src/routes/Badges.svelte
fix pagination and display y-scale values also in %
reduce imported size by 80KB by explicitly load registrables
> Fix contribution graph pagination and more

- backend/db/contributions.go
- frontend/src/routes/Badges.svelte
Also remove the weight column, as this information is no longer available on the contribution.
> Fix `claimed` information not being displayed

- monitoring/grafana/provisioning/dashboards/flatfeestack.json
- monitoring/grafana/provisioning/dashboards/postgresql.json
> Add new dashboard dedicated for FlatFeeStack metrics

- frontend/src/routes/ForwardGitEmail.svelte
redirect if confirm git email fails to prevent
user seeing blank page
> navigate to search (or login) in case of error

- frontend/src/routes/ConfirmForgot.svelte
- frontend/src/routes/ConfirmInvite.svelte
- frontend/src/routes/Signup.svelte
to keep same style/behaviour as in regular sign up
> add pw confirm field for pw reset and invite signup

- frontend/src/app.css
- frontend/src/components/Header.svelte
- frontend/src/components/Navigation.svelte
- frontend/src/components/PaymentSelection.svelte
- frontend/src/components/PaymentTabs/CryptoTab.svelte
- frontend/src/components/PaymentTabs/FiatTab.svelte
- frontend/src/components/RepoCard.svelte
- frontend/src/components/SearchResult.svelte
- frontend/src/components/Tabs.svelte
- frontend/src/routes/Badges.svelte
- frontend/src/routes/Income.svelte
- frontend/src/routes/Invitations.svelte
- frontend/src/routes/Payments.svelte
- frontend/src/routes/Search.svelte
- frontend/src/routes/Settings.svelte
A second version for the responsive, a bit cleaner this time
(plus I didn't wanna rebase sooo yeahh... but mainly because of cleaner hehe)
> First Responsive Improvements

- backend/api/users.go
- frontend/src/components/PaymentTabs/FiatTab.svelte
- frontend/src/ts/services.ts
- add some missing types in the frontend 
- Link newly created payment method with existing Stripe customer
> Small credit card improvements
